package com.wtms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOperatecontent<M extends BaseOperatecontent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOperateTicketId(java.lang.Integer operateTicketId) {
		set("operateTicketId", operateTicketId);
		return (M)this;
	}
	
	public java.lang.Integer getOperateTicketId() {
		return getInt("operateTicketId");
	}

	public M setOptitemid(java.lang.Integer optitemid) {
		set("optitemid", optitemid);
		return (M)this;
	}
	
	public java.lang.Integer getOptitemid() {
		return getInt("optitemid");
	}

	public M setOptItemContent(java.lang.String optItemContent) {
		set("optItemContent", optItemContent);
		return (M)this;
	}
	
	public java.lang.String getOptItemContent() {
		return getStr("optItemContent");
	}

	public M setDangerPointIds(java.lang.String dangerPointIds) {
		set("dangerPointIds", dangerPointIds);
		return (M)this;
	}
	
	public java.lang.String getDangerPointIds() {
		return getStr("dangerPointIds");
	}

}
