package com.wtms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setWorknum(java.lang.String worknum) {
		set("worknum", worknum);
		return (M)this;
	}
	
	public java.lang.String getWorknum() {
		return getStr("worknum");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setDepartmentIds(java.lang.String departmentIds) {
		set("departmentIds", departmentIds);
		return (M)this;
	}
	
	public java.lang.String getDepartmentIds() {
		return getStr("departmentIds");
	}

	public M setBroleIds(java.lang.String broleIds) {
		set("broleIds", broleIds);
		return (M)this;
	}
	
	public java.lang.String getBroleIds() {
		return getStr("broleIds");
	}

	public M setRoleIds(java.lang.String roleIds) {
		set("roleIds", roleIds);
		return (M)this;
	}
	
	public java.lang.String getRoleIds() {
		return getStr("roleIds");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
		return (M)this;
	}
	
	public java.util.Date getCreatedAt() {
		return get("created_at");
	}

	public M setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
		return (M)this;
	}
	
	public java.util.Date getUpdatedAt() {
		return get("updated_at");
	}

	public M setDeletedAt(java.util.Date deletedAt) {
		set("deleted_at", deletedAt);
		return (M)this;
	}
	
	public java.util.Date getDeletedAt() {
		return get("deleted_at");
	}

}
