package com.wtms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEquipments<M extends BaseEquipments<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
		return (M)this;
	}
	
	public java.lang.Integer getParentid() {
		return getInt("parentid");
	}

	public M setHasChildren(java.lang.Boolean hasChildren) {
		set("hasChildren", hasChildren);
		return (M)this;
	}
	
	public java.lang.Boolean getHasChildren() {
		return get("hasChildren");
	}

}
