package com.wtms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
		return (M)this;
	}
	
	public java.lang.Integer getParentid() {
		return getInt("parentid");
	}

	public M setOrderid(java.lang.Integer orderid) {
		set("orderid", orderid);
		return (M)this;
	}
	
	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}

}
