package com.wtms.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBrole<M extends BaseBrole<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setFstateIds(java.lang.String fstateIds) {
		set("fstateIds", fstateIds);
		return (M)this;
	}
	
	public java.lang.String getFstateIds() {
		return getStr("fstateIds");
	}

	public M setWorkTicketStatesIds(java.lang.String workTicketStatesIds) {
		set("workTicketStatesIds", workTicketStatesIds);
		return (M)this;
	}
	
	public java.lang.String getWorkTicketStatesIds() {
		return getStr("workTicketStatesIds");
	}

	public M setOperateTicketStatesIds(java.lang.String operateTicketStatesIds) {
		set("operateTicketStatesIds", operateTicketStatesIds);
		return (M)this;
	}
	
	public java.lang.String getOperateTicketStatesIds() {
		return getStr("operateTicketStatesIds");
	}

}
