package com.wtms.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("wf_brole", "id", Brole.class);
		arp.addMapping("wf_department", "id", Department.class);
		arp.addMapping("wf_equipments", "id", Equipments.class);
		arp.addMapping("wf_fault", "id", Fault.class);
		arp.addMapping("wf_flevel", "id", Flevel.class);
		arp.addMapping("wf_fstate", "id", Fstate.class);
		arp.addMapping("wf_kks", "id", Kks.class);
		arp.addMapping("wf_menu", "id", Menu.class);
		arp.addMapping("wf_operatecontent", "id", Operatecontent.class);
		arp.addMapping("wf_operateticketstate", "id", Operateticketstate.class);
		arp.addMapping("wf_permission", "id", Permission.class);
		arp.addMapping("wf_position", "id", Position.class);
		arp.addMapping("wf_role", "id", Role.class);
		arp.addMapping("wf_role_menu", "id", RoleMenu.class);
		arp.addMapping("wf_role_permission", "id", RolePermission.class);
		arp.addMapping("wf_user", "id", User.class);
		arp.addMapping("wf_user_role", "id", UserRole.class);
		arp.addMapping("wf_workticketstate", "id", Workticketstate.class);
	}
}

