package com.wtms.common.model;

import com.wtms.common.model.base.BaseBrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brole extends BaseBrole<Brole> {
	public static final Brole dao = new Brole().dao();
}
