package com.wtms.common.model;

import com.wtms.common.model.base.BaseEquipments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equipments extends BaseEquipments<Equipments> {
	public static final Equipments dao = new Equipments().dao();
}
