package com.wtms.common.model;

import com.wtms.common.model.base.BaseFault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fault extends BaseFault<Fault> {
	public static final Fault dao = new Fault().dao();
}
