package com.wtms.common.model;

import com.wtms.common.model.base.BaseFlevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Flevel extends BaseFlevel<Flevel> {
	public static final Flevel dao = new Flevel().dao();
}
