package com.wtms.common.model;

import com.wtms.common.model.base.BaseFstate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fstate extends BaseFstate<Fstate> {
	public static final Fstate dao = new Fstate().dao();
}
