package com.wtms.common.model;

import com.wtms.common.model.base.BaseKks;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kks extends BaseKks<Kks> {
	public static final Kks dao = new Kks().dao();
}
