package com.wtms.common.model;

import com.wtms.common.model.base.BaseOperatecontent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operatecontent extends BaseOperatecontent<Operatecontent> {
	public static final Operatecontent dao = new Operatecontent().dao();
}
