package com.wtms.common.model;

import com.wtms.common.model.base.BaseOperateticketstate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operateticketstate extends BaseOperateticketstate<Operateticketstate> {
	public static final Operateticketstate dao = new Operateticketstate().dao();
}
