package com.wtms.common.model;

import com.wtms.common.model.base.BasePosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Position extends BasePosition<Position> {
	public static final Position dao = new Position().dao();
}
