package com.wtms.common.model;

import com.wtms.common.model.base.BaseRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
	public static final RoleMenu dao = new RoleMenu().dao();
}
