package com.wtms.common.model;

import com.wtms.common.model.base.BaseWorkticketstate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workticketstate extends BaseWorkticketstate<Workticketstate> {
	public static final Workticketstate dao = new Workticketstate().dao();
}
